import { Poppins } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/Providers/Session-Providers";

const poppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ['400', '500']
});

export const metadata = {
  title: "Xpensify - Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap" />
      </head>
      <body
        className={`${poppins.className} antialiased`}
      >
       
          <SessionProvider>
            {children}
          </SessionProvider>
      </body>
    </html>
  );
}
